# Generated by Django 4.1.4 on 2024-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('gif_url', models.URLField()),
                ('language', models.CharField(max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
